name: Weekly LinguaVitamin arXiv (cs.DC) Run

on:
  schedule:
    - cron: "30 14 * * 5"       # Runs at 07:30 PDT on Fridays
  workflow_dispatch:            # Also allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "bot@users.noreply.github.com"
          git config --global user.name "LinguaVitamin Bot"

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/sliuxl/LinguaVitaminArxiv.git

      - name: Clone LinguaVitaminArxiv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/sliuxl/LinguaVitaminArxiv.git /tmp/LinguaVitaminArxiv
          cd /tmp/LinguaVitaminArxiv
          TODAY=$(date +%Y-%m-%d)
          git push origin --delete AUTO--$TODAY--arxiv-cs__DC || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -e .

      - name: Run main script
        env:
          GITHUB_TOKEN:         ${{ secrets.GH_TOKEN }}
          SMTP_SERVER:          ${{ secrets.SMTP_SERVER }}
          SMTP_USER:            ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD:        ${{ secrets.SMTP_PASSWORD }}
          FROM_EMAIL:           ${{ secrets.FROM_EMAIL }}
          TO_EMAILS:            ${{ secrets.TO_EMAILS }}
        run: |
          python src/lingua_vitamin/main.py \
            --github_token      $GITHUB_TOKEN \
            --smtp_server       "$SMTP_SERVER" \
            --smtp_user         "$SMTP_USER" \
            --smtp_password     "$SMTP_PASSWORD" \
            --from_email        "$FROM_EMAIL" \
            --to_emails         $TO_EMAILS \
            \
            --arxiv cs.DC \
            --arxiv_num_days 8 \
            --github_repo sliuxl/LinguaVitaminArxiv \
            --num_articles 3000 \
            --target_langs de zh\
            \
            --output_root /tmp/LinguaVitaminArxiv \
            --output_md  _posts/arxiv/{year}/{month} \
            --output_csv csv/arxiv/{year}/{month}

      - name: Merge PR for LinguaVitaminArxiv
        run: |
          cd /tmp/LinguaVitaminArxiv
          TODAY=$(date +%Y-%m-%d)
          BRANCH=AUTO--$TODAY--arxiv-cs__DC
          git push origin $BRANCH:main
          git push origin --delete $BRANCH || true
